---
roots:
  Webroot:
    type: "normal"
    path:
      system: "~/Sites"
      web: "/"
  Videos:
    type: "media"
    path:
      system: "~/Videos"
      web: "/Videos"
  Music:
    type: "media"
    path:
      system: "/media/nathanpc/Second-HDD/Music"
      web: "/Music"
